In [3]:
!pip install numpy
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [4]:
# Create 1D array
arr = np.array([1,2,3])
print (arr)

[1 2 3]

In [5]:
# create 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print (arr2)

[[1 2 3]
 [4 5 6]]

In [6]:
# create 3D array
arr3 = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [7]:
# array of zeros
arr = np.zeros (4)
print (arr)

[0. 0. 0. 0.]

In [8]:
# array of 1's
arr = np.ones(4)
print (arr)

[1. 1. 1. 1.]

In [9]:
# print numpy array in given range using np.arange() function
arr = np.arange(5)
print(arr)

arr_odd = np.arange (1,9,2)
print(arr_odd)

[0 1 2 3 4]
[1 3 5 7]

In [10]:
# print random number using np.random.rand() & np.random.randint function

arr = np.random.rand(6)
print ("random numbers using np.random.rand is : ",arr)

arr2 = np.random.randint (6)
print ("random numbers using np.random.randint is : ", arr2)

random numbers using np.random.rand is :  [0.92587897 0.86629065 0.84693097 0.18468574 0.0675999  0.56622116]
random numbers using np.random.randint is :  1

In [11]:
# convert int array into float array
int_array = np.array([1,2,3])
print (int_array)
float_array = np.array (int_array, dtype = float)
print (float_array)

# one more way we can convert it using .astype()
float_array2 = int_array.astype(float)
print (float_array2)

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]

In [12]:
# check the dimension and shape of array

arr = np.array([[1,2,3],[4,5,6]])
print (arr.ndim)
print (arr.shape)

2
(2, 3)

In [13]:
# to save the array
arr = np.array([[1,2,3],[4,5,6]])
save = np.save("arr.npy" , arr)

# to load the array
loaded_array = np.load("arr.npy")
print (loaded_array)

[[1 2 3]
 [4 5 6]]

In [14]:
# perform arithematic operations on np array
a=np.array([1,2,3])
b=np.array([4,5,6])
print ("addition of 2 array is: ", np.add(a,b))
print ("subtraction of 2 array is: ", np.subtract(a,b))
print ("multiplication of 2 array is: ", np.multiply(a,b))
print ("division of 2 array is: ", np.divide(a,b))

addition of 2 array is:  [5 7 9]
subtraction of 2 array is:  [-3 -3 -3]
multiplication of 2 array is:  [ 4 10 18]
division of 2 array is:  [0.25 0.4  0.5 ]

Data Wrangling : dealing with missing value, reshape your data

In [15]:
#assign data

data={'Name': ['Yamini','Pratik','Pratiksha','Avinash'],
      'Age' : [20,22,24,25],
      'Gender' : ['F','M','F','M'],
      'Marks' : [90,95,'NAN',99]}
df=pd.DataFrame(data)
df

        Name  Age Gender Marks
0     Yamini   20      F    90
1     Pratik   22      M    95
2  Pratiksha   24      F   NAN
3    Avinash   25      M    99

In [16]:
# Dealing with missing value
c=avg=0
for i in df ["Marks"]:
  if str(i).isnumeric():
    c += 1
    avg += i
avg /= c
df = df.replace (to_replace = "NAN", value = avg)
df

/tmp/ipykernel_3752/1553556463.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace (to_replace = "NAN", value = avg)

        Name  Age Gender      Marks
0     Yamini   20      F  90.000000
1     Pratik   22      M  95.000000
2  Pratiksha   24      F  94.666667
3    Avinash   25      M  99.000000

In [29]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Slice this array to display last column [3],[6],[9]
print (array[:,2])
print (array[:,2:3])

# slice a array to display last 2 digit of middle array; i.e [5,6]
print (array[1,1:])

[3 6 9]
[[3]
 [6]
 [9]]
[5 6]